// gen-docs walks the api source and emits Markdown reference docs into
// cloud/web/docs/reference/. Run from the repo root or anywhere — paths are
// computed relative to this source file via runtime.Caller.
//
// Generated outputs:
//   - reference/routes.md     — HTTP route table (method, path, auth, notes)
//   - reference/cel-env.md    — CEL variables exposed to policy expressions
//   - reference/error-codes.md — Stable error codes returned by the API
//
// Re-run with:  go run ./cmd/gen-docs   from cloud/api/.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strings"
	"time"
)

func main() {
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		die("runtime.Caller failed")
	}
	apiRoot := filepath.Clean(filepath.Join(filepath.Dir(thisFile), "..", ".."))
	repoRoot := filepath.Clean(filepath.Join(apiRoot, "..", ".."))
	outDir := filepath.Join(repoRoot, "cloud", "web", "docs", "reference")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		die("mkdir: %v", err)
	}

	if err := writeRoutes(apiRoot, outDir); err != nil {
		die("routes: %v", err)
	}
	if err := writeCELEnv(apiRoot, outDir); err != nil {
		die("cel-env: %v", err)
	}
	if err := writeErrorCodes(apiRoot, outDir); err != nil {
		die("error-codes: %v", err)
	}
	fmt.Fprintf(os.Stderr, "wrote reference docs to %s\n", outDir)
}

const generatedBanner = `<!-- AUTOGENERATED by cloud/api/cmd/gen-docs. Re-run: cd cloud/api && go run ./cmd/gen-docs -->`

func writeRoutes(apiRoot, outDir string) error {
	src, err := os.ReadFile(filepath.Join(apiRoot, "internal", "api", "server.go"))
	if err != nil {
		return err
	}
	routes := parseRoutes(string(src))

	var b strings.Builder
	fmt.Fprintf(&b, "%s\n\n", generatedBanner)
	b.WriteString("# HTTP route reference\n\n")
	b.WriteString("Every HTTP endpoint Bright Guard's control plane exposes. ")
	b.WriteString("The auth column says what the route demands:\n\n")
	b.WriteString("- **public** — no credential required.\n")
	b.WriteString("- **session** — cookie or device-flow bearer token; the user must be signed in.\n")
	b.WriteString("- **org member** — session plus membership of the org in the URL path.\n")
	b.WriteString("- **org admin** — session plus owner/admin role in the org.\n")
	b.WriteString("- **platform admin** — session plus the platform-admin role.\n")
	b.WriteString("- **gateway** — gateway-issued bearer credential (no cookies).\n\n")
	b.WriteString("| Method | Path | Auth | Handler |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, r := range routes {
		fmt.Fprintf(&b, "| %s | `%s` | %s | `%s` |\n", r.Method, r.Path, r.Auth, r.Handler)
	}
	fmt.Fprintf(&b, "\n_Generated %s from `cloud/api/internal/api/server.go`._\n",
		time.Now().UTC().Format("2006-01-02"))

	return os.WriteFile(filepath.Join(outDir, "routes.md"), []byte(b.String()), 0o644)
}

type route struct {
	Method  string
	Path    string
	Auth    string
	Handler string
}

// parseRoutes is a regex-based walker over server.go. It tracks four pieces of
// state by indentation:
//
//   - Whether we're inside the `r.Group(... auth.RequireUser ...)` block
//     (session-required).
//   - Whether we're inside a `r.Route("/api/orgs/{orgId}", ...)` block
//     (orgMember). A nested `auth.RequireOrgRole(...)` group flips to org admin.
//   - Whether we're inside the platform-admin block.
//   - Whether we're inside the gateway-bearer group.
//
// Brace counting is sufficient because server.go has consistent style. If the
// router setup is ever refactored to be more dynamic this generator will need
// to change.
func parseRoutes(src string) []route {
	var routes []route

	lines := strings.Split(src, "\n")
	verbRe := regexp.MustCompile(`r\.(Get|Post|Put|Patch|Delete|Mount)\(\s*"([^"]+)"\s*,\s*([^)]+)\)`)
	routeRe := regexp.MustCompile(`r\.Route\(\s*"([^"]+)"`)

	type scope struct {
		brace      int
		pathPrefix string
		auth       string
	}
	var stack []scope
	stack = append(stack, scope{brace: 0, pathPrefix: "", auth: "public"})

	currentBrace := 0
	for _, line := range lines {
		// Track brace balance, ignoring braces inside double-quoted strings.
		// Chi paths embed parameters like `{orgId}` that must not count.
		open, closeB := countBraces(line)
		netBefore := currentBrace

		// Detect auth-shifting introductions inside the current scope.
		// These take effect on the NEXT scope we push.
		nextAuth := ""
		if strings.Contains(line, "auth.RequireUser") {
			nextAuth = "session"
		} else if strings.Contains(line, "auth.RequireOrgRole") {
			nextAuth = "org admin"
		} else if strings.Contains(line, "auth.RequirePlatformAdmin") {
			nextAuth = "platform admin"
		} else if strings.Contains(line, "gatewayBearer") {
			nextAuth = "gateway"
		} else if strings.Contains(line, "orgMember") {
			nextAuth = "org member"
		}

		// r.Route(...) introduces a path prefix scope.
		if m := routeRe.FindStringSubmatch(line); m != nil {
			top := stack[len(stack)-1]
			s := scope{
				brace:      netBefore + open,
				pathPrefix: top.pathPrefix + m[1],
				auth:       top.auth,
			}
			stack = append(stack, s)
			currentBrace += open - closeB
			continue
		}

		// r.Group(...) opens an auth scope (possibly).
		if strings.Contains(line, "r.Group(func") {
			top := stack[len(stack)-1]
			s := scope{
				brace:      netBefore + open,
				pathPrefix: top.pathPrefix,
				auth:       top.auth,
			}
			stack = append(stack, s)
			currentBrace += open - closeB
			continue
		}

		// If this line carries an auth-shifting middleware call (r.Use(...)),
		// apply it to the innermost scope.
		if nextAuth != "" && strings.Contains(line, "r.Use(") {
			stack[len(stack)-1].auth = nextAuth
		}

		// Verb (route) extraction.
		if m := verbRe.FindStringSubmatch(line); m != nil {
			top := stack[len(stack)-1]
			method := strings.ToUpper(m[1])
			path := top.pathPrefix + m[2]
			handler := strings.TrimSpace(m[3])
			handler = strings.TrimPrefix(handler, "s.")
			// Anonymous inline handlers (e.g. healthz) come through with the
			// `func(...)` prefix — collapse those to a placeholder.
			if strings.HasPrefix(handler, "func(") {
				handler = "(inline)"
			}
			auth := top.auth
			if method == "MOUNT" {
				continue
			}
			// /v1/gateway/register is intentionally bearer-less.
			if path == "/v1/gateway/register" {
				auth = "public (enrollmentToken in body)"
			}
			routes = append(routes, route{Method: method, Path: path, Auth: auth, Handler: handler})
		}

		currentBrace += open - closeB
		// Pop any scopes whose brace count exceeds current depth.
		for len(stack) > 1 && stack[len(stack)-1].brace > currentBrace {
			stack = stack[:len(stack)-1]
		}
	}

	// Dedupe by (method, path). server.go registers a fallback handler for
	// /auth/google/start inside an else branch — both register-calls hit the
	// scanner. Keep the first occurrence (the configured-google handler).
	seen := map[string]bool{}
	deduped := routes[:0]
	for _, r := range routes {
		k := r.Method + " " + r.Path
		if seen[k] {
			continue
		}
		seen[k] = true
		deduped = append(deduped, r)
	}
	routes = deduped

	sort.SliceStable(routes, func(i, j int) bool {
		if routes[i].Path != routes[j].Path {
			return routes[i].Path < routes[j].Path
		}
		return routes[i].Method < routes[j].Method
	})
	return routes
}

func countBraces(line string) (open, closeB int) {
	inStr := false
	escape := false
	for _, r := range line {
		switch {
		case escape:
			escape = false
		case r == '\\':
			escape = true
		case r == '"':
			inStr = !inStr
		case inStr:
			// skip
		case r == '{':
			open++
		case r == '}':
			closeB++
		}
	}
	return open, closeB
}

func writeCELEnv(apiRoot, outDir string) error {
	src, err := os.ReadFile(filepath.Join(apiRoot, "internal", "policy", "policy.go"))
	if err != nil {
		return err
	}

	// Pull each cel.Variable("name", <type>) declaration. We can't use a
	// simple regex because the type argument itself contains parentheses
	// (cel.MapType(...)). Find the call site with a regex, then walk parens
	// manually to extract the second argument.
	type celVar struct{ Name, Type string }
	var vars []celVar
	nameRe := regexp.MustCompile(`cel\.Variable\(\s*"([^"]+)"\s*,\s*`)
	srcStr := string(src)
	for _, idx := range nameRe.FindAllStringSubmatchIndex(srcStr, -1) {
		name := srcStr[idx[2]:idx[3]]
		// Walk from idx[1] until the matching close paren.
		depth := 1
		start := idx[1]
		end := start
		for i := start; i < len(srcStr); i++ {
			switch srcStr[i] {
			case '(':
				depth++
			case ')':
				depth--
				if depth == 0 {
					end = i
					goto done
				}
			}
		}
	done:
		typ := strings.TrimSpace(srcStr[start:end])
		vars = append(vars, celVar{Name: name, Type: typ})
	}

	descriptions := map[string]string{
		"caller":     "Claimed caller identity for the invocation — `caller.agent`, `caller.user`, or any other field the gateway forwarded.",
		"server":     "MCP server name, address, and transport. `server.name`, `server.address`, `server.transport`.",
		"capability": "Capability being invoked. `capability.kind` (tool / resource / prompt), `capability.name`, `capability.description`.",
		"at":         "Invocation timestamp (UTC).",
		"status":     "Invocation status the gateway observed. `\"ok\"`, `\"error\"`, or `\"denied\"`. A denied status from one policy makes downstream policies see `status == \"denied\"`.",
	}

	// Pull the cost limit.
	costRe := regexp.MustCompile(`evalCostLimit\s+uint64\s*=\s*([\d_]+)`)
	costMatch := costRe.FindStringSubmatch(string(src))
	cost := "(see policy.go)"
	if costMatch != nil {
		cost = strings.ReplaceAll(costMatch[1], "_", "")
	}

	var b strings.Builder
	fmt.Fprintf(&b, "%s\n\n", generatedBanner)
	b.WriteString("# CEL environment reference\n\n")
	b.WriteString("Policies are CEL expressions that must return a boolean. ")
	b.WriteString("They evaluate inside a sandboxed environment with the variables below; ")
	b.WriteString("anything else is a compile-time error.\n\n")
	b.WriteString("## Variables\n\n")
	b.WriteString("| Variable | Type | Description |\n")
	b.WriteString("|---|---|---|\n")
	for _, v := range vars {
		desc := descriptions[v.Name]
		if desc == "" {
			desc = "(no description)"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", v.Name, normalizeCELType(v.Type), desc)
	}

	b.WriteString("\n## Cost limit\n\n")
	fmt.Fprintf(&b, "Every evaluation runs under a hard cost limit of **%s units**. ", cost)
	b.WriteString("Each CEL operation costs roughly 1 unit. The example expressions in the docs cost <10. ")
	b.WriteString("If a policy exceeds the limit it errors out — the invocation is _not_ denied; the policy is treated as having not matched, and the error is logged.\n\n")

	b.WriteString("## Output type\n\n")
	b.WriteString("Expressions are required to evaluate to `bool`. Other return types are rejected at compile time.\n\n")

	b.WriteString("## Disallowed extensions\n\n")
	b.WriteString("`cel.ext.Strings()` and other regex helpers are deliberately **not** enabled. ")
	b.WriteString("Tenant-supplied regexes are a backtracking DoS surface. ")
	b.WriteString("If you need substring matching, use the built-in `.startsWith()`, `.endsWith()`, and `.contains()` methods on string values.\n\n")

	fmt.Fprintf(&b, "_Generated %s from `cloud/api/internal/policy/policy.go`._\n",
		time.Now().UTC().Format("2006-01-02"))

	return os.WriteFile(filepath.Join(outDir, "cel-env.md"), []byte(b.String()), 0o644)
}

func normalizeCELType(s string) string {
	s = strings.TrimSpace(s)
	switch s {
	case "cel.MapType(cel.StringType, cel.DynType)":
		return "`map<string, dyn>`"
	case "cel.MapType(cel.StringType, cel.StringType)":
		return "`map<string, string>`"
	case "cel.TimestampType":
		return "`google.protobuf.Timestamp`"
	case "cel.StringType":
		return "`string`"
	case "cel.IntType":
		return "`int`"
	case "cel.BoolType":
		return "`bool`"
	default:
		return "`" + s + "`"
	}
}

func writeErrorCodes(apiRoot, outDir string) error {
	// Walk every .go file under internal/api/ and internal/auth/. Extract every
	// writeError(w, http.StatusXxx, "code", "message") triple. Dedup by code,
	// remembering the most common message.
	type codeUsage struct {
		Code    string
		Status  string
		Sources map[string]int // example message -> count
	}
	// Key on (status, code) so the same code at multiple HTTP statuses each
	// gets its own row (e.g. `expired` for both 410 Gone and 401 Unauthorized).
	codes := map[string]*codeUsage{}

	// Two flavours of writeError call:
	//   writeError(w, http.StatusFoo, "code", "literal message")
	//   writeError(w, http.StatusFoo, "code", err.Error())
	//   writeError(w, http.StatusFoo, "code",
	//     "multiline message")
	// We need just the (status, code) pair; if the next argument is a string
	// literal we'll keep it as the example, otherwise we leave the example
	// empty for that occurrence.
	callRe := regexp.MustCompile(`writeError\(\s*w\s*,\s*http\.Status([A-Za-z]+)\s*,\s*"([a-z_0-9]+)"\s*,\s*([^)]*)`)
	literalRe := regexp.MustCompile(`^"([^"]*)"`)

	walk := func(dir string) error {
		return filepath.Walk(dir, func(p string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if info.IsDir() {
				return nil
			}
			if !strings.HasSuffix(p, ".go") || strings.HasSuffix(p, "_test.go") {
				return nil
			}
			src, err := os.ReadFile(p)
			if err != nil {
				return err
			}
			for _, m := range callRe.FindAllStringSubmatch(string(src), -1) {
				status, code, tail := m[1], m[2], strings.TrimSpace(m[3])
				key := status + "|" + code
				u, ok := codes[key]
				if !ok {
					u = &codeUsage{Code: code, Status: status, Sources: map[string]int{}}
					codes[key] = u
				}
				// Only keep the example if it's a string literal — `err.Error()`
				// and friends aren't useful in a static reference.
				if lm := literalRe.FindStringSubmatch(tail); lm != nil {
					u.Sources[lm[1]]++
				}
			}
			return nil
		})
	}
	if err := walk(filepath.Join(apiRoot, "internal", "api")); err != nil {
		return err
	}
	if err := walk(filepath.Join(apiRoot, "internal", "auth")); err != nil {
		return err
	}

	type row struct {
		Code, Status, Example string
	}
	var rows []row
	for _, u := range codes {
		// Pick the most common example message; ties broken alphabetically.
		var examples []string
		for m := range u.Sources {
			examples = append(examples, m)
		}
		sort.Slice(examples, func(i, j int) bool {
			if u.Sources[examples[i]] != u.Sources[examples[j]] {
				return u.Sources[examples[i]] > u.Sources[examples[j]]
			}
			return examples[i] < examples[j]
		})
		ex := ""
		if len(examples) > 0 {
			ex = examples[0]
		}
		rows = append(rows, row{Code: u.Code, Status: u.Status, Example: ex})
	}
	sort.Slice(rows, func(i, j int) bool {
		if statusOrder(rows[i].Status) != statusOrder(rows[j].Status) {
			return statusOrder(rows[i].Status) < statusOrder(rows[j].Status)
		}
		return rows[i].Code < rows[j].Code
	})

	hints := map[string]string{
		"bad_request":              "Request body was not valid JSON or was missing required fields.",
		"invalid_request":          "Validation error in the request — e.g. malformed URL, unknown enum value.",
		"invalid_org_id":           "The `orgId` in the URL or body could not be parsed as a UUID.",
		"invalid_expression":       "A CEL policy expression failed to compile.",
		"unauthorized":             "No valid session cookie or bearer token was supplied.",
		"expired":                  "The credential (session, device code) has expired.",
		"forbidden":                "Authenticated but not authorised — typically wrong org role.",
		"denied":                   "Device authorization was denied by the user.",
		"not_found":                "Resource does not exist or is not visible to this caller.",
		"authorization_pending":    "Device-flow poll: user has not yet approved or denied. Retry after `interval` seconds.",
		"conflict":                 "Resource already exists or violates a uniqueness constraint.",
		"name_conflict":            "An object of the requested name already exists in this org.",
		"already_invited":          "The target user already has a pending invitation to this org.",
		"already_member":           "The target user is already a member of this org.",
		"dcr_unsupported":          "Upstream identity provider does not support OAuth2 Dynamic Client Registration.",
		"not_registered":           "Gateway credential is unknown to the control plane — re-enroll the gateway.",
		"google_oauth_unconfigured": "Google OAuth client credentials are not set on this deployment.",
		"policy_engine_unconfigured": "The CEL policy engine failed to initialise at startup.",
		"scheduler_unconfigured":   "The background scheduler is not running (typically only in test builds).",
		"upstream_failure":         "An external service the control plane depends on returned an error.",
		"internal":                 "Unhandled server-side error. The request ID in the response headers is the link to logs.",
	}

	var b strings.Builder
	fmt.Fprintf(&b, "%s\n\n", generatedBanner)
	b.WriteString("# API error codes\n\n")
	b.WriteString("Every non-2xx response from `bright-guard` returns a JSON envelope:\n\n")
	b.WriteString("```json\n{ \"error\": { \"code\": \"invalid_request\", \"message\": \"endpointUrl is required\" } }\n```\n\n")
	b.WriteString("The `code` is stable and safe to switch on; the `message` is human-facing and may change. Codes are scoped to the HTTP status they were returned with.\n\n")
	b.WriteString("| HTTP | Code | Meaning | Example message |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, r := range rows {
		hint := hints[r.Code]
		if hint == "" {
			hint = "(uncategorised)"
		}
		fmt.Fprintf(&b, "| %d %s | `%s` | %s | %s |\n", statusOrder(r.Status), r.Status, r.Code, hint, codeFence(r.Example))
	}
	fmt.Fprintf(&b, "\n_Generated %s by scanning every `writeError(...)` call under `cloud/api/internal/api/` and `cloud/api/internal/auth/`._\n",
		time.Now().UTC().Format("2006-01-02"))
	return os.WriteFile(filepath.Join(outDir, "error-codes.md"), []byte(b.String()), 0o644)
}

func codeFence(s string) string {
	if s == "" {
		return ""
	}
	// Pipes in Markdown tables need escaping.
	s = strings.ReplaceAll(s, "|", `\|`)
	return "`" + s + "`"
}

func statusOrder(name string) int {
	switch name {
	case "BadRequest":
		return 400
	case "Unauthorized":
		return 401
	case "Forbidden":
		return 403
	case "NotFound":
		return 404
	case "Conflict":
		return 409
	case "Gone":
		return 410
	case "PreconditionRequired":
		return 428
	case "UnprocessableEntity":
		return 422
	case "InternalServerError":
		return 500
	case "BadGateway":
		return 502
	case "ServiceUnavailable":
		return 503
	default:
		return 999
	}
}

func die(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
